name: Docs Publish
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    if: github.repository_owner == 'Qiskit-Community'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz pandoc
    - name: Build docs
      env:
        QISKIT_DOCS_BUILD_TUTORIALS: 'always'
      run: PROD_BUILD=1 uvx --with tox-uv tox -edocs
    - name: Bypass Jekyll Processing # Necessary for setting the correct css path
      run: touch docs/_build/html/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html/
        clean-exclude: |
          stable/*
          dev/*
